### PR TITLE
fix: Remove Stackdriver from code samples

### PR DESCRIPTION
**Pull request by lahirumaramba**
- The Stack Driver name is retired. Removed it from the code samples.
- The code samples are used in https://firebase.google.com/docs/functions/reporting-errors

Internal: b/206234506

### CODE REVIEW

**Review by ace-n — APPROVED** [review]

**Review by sofisl — APPROVED** [review]

**Comment by lahirumaramba** [comment]
Hey team, I don't have permission to merge this PR. Let me know if further changes are needed from my side. Thanks!

**Comment by ace-n** [comment]
Test failure is due to this branch being on a fork.

@sofisl can you merge this? (If not, I can try and admin-merge **if** you're OK w/ it.)

**Comment by sofisl** [comment]
@ace-n, go ahead and admin merge!

**Comment by ace-n** [comment]
This has been obviated by #2306. 🙂

**Pull request closed without merging**
