### PR TITLE
Speech: Use all results, instead of just the first.

### PR DESCRIPTION
**Pull request by jerjou**
Addresses #465

### CODE REVIEW

**Comment by jerjou** [comment]
Hrm... I don't understand why the tests are failing. Does `.includes` break when there are newlines, or something? Also, I don't know how to run the tests :-(

**Comment by jmdobry** [comment]
See [Running the tests](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/master/speech#running-the-tests)

**Comment by jerjou** [comment]
```
root@3c53645a3ecb:~/nodejs-docs-samples/speech# npm test

> nodejs-docs-samples-speech@0.0.1 pretest /root/nodejs-docs-samples/speech
> npm run lint


> nodejs-docs-samples-speech@0.0.1 lint /root/nodejs-docs-samples/speech
> samples lint

sh: 1: samples: not found

npm ERR! Linux 4.4.0-75-generic
npm ERR! argv "/nodejs/bin/node" "/nodejs/bin/npm" "run" "lint"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! nodejs-docs-samples-speech@0.0.1 lint: `samples lint`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the nodejs-docs-samples-speech@0.0.1 lint script 'samples lint'.
npm ERR! This is most likely a problem with the nodejs-docs-samples-speech package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     samples lint
npm ERR! You can get their info via:
npm ERR!     npm owner ls nodejs-docs-samples-speech
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/nodejs-docs-samples/speech/npm-debug.log
npm ERR! Test failed.  See above for more details.
root@3c53645a3ecb:~/nodejs-docs-samples/speech#      
```

I appear to be missing a `samples` command? I had done an `npm install` in the root dir.. this is on the `google/nodejs` docker image.

**Comment by jmdobry** [comment]
Have you run `npm install` in `/root/nodejs-docs-samples/speech`?

**Comment by jerjou** [comment]
Yeah

**Comment by jmdobry** [comment]
Here's what I got:

```
$ npm install -g semistandard
/Users/jdobry/.nvm/versions/node/v6.11.1/bin/semistandard -> /Users/jdobry/.nvm/versions/node/v6.11.1/lib/node_modules/semistandard/bin/cmd.js
+ semistandard@11.0.0
updated 4 packages in 4.719s
$ cd ~
$ git clone git@github.com:GoogleCloudPlatform/nodejs-docs-samples.git
Cloning into 'nodejs-docs-samples'...
remote: Counting objects: 8114, done.
remote: Compressing objects: 100% (111/111), done.
remote: Total 8114 (delta 52), reused 59 (delta 29), pack-reused 7974
Receiving objects: 100% (8114/8114), 13.05 MiB | 1.79 MiB/s, done.
Resolving deltas: 100% (5056/5056), done.
$ cd nodejs-docs-samples/speech/
$ git checkout -b speech-allresults origin/speech-allresults
Branch speech-allresults set up to track remote branch speech-allresults from origin.
Switched to a new branch 'speech-allresults'
$ npm install

> fsevents@1.1.2 install /Users/jdobry/nodejs-docs-samples/speech/node_modules/fsevents
> node install

[fsevents] Success: "/Users/jdobry/nodejs-docs-samples/speech/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> grpc@1.4.1 install /Users/jdobry/nodejs-docs-samples/speech/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

[grpc] Success: "/Users/jdobry/nodejs-docs-samples/speech/node_modules/grpc/src/node/extension_binary/grpc_node.node" is installed via remote
npm notice created a lockfile as package-lock.json. You should commit this file.
added 831 packages in 21.851s
$ set -x GCLOUD_PROJECT nodejs-docs-samples
$ set -x GOOGLE_APPLICATION_CREDENTIALS /Users/jdobry/key.json
$ npm test

> nodejs-docs-samples-speech@0.0.1 pretest /Users/jdobry/nodejs-docs-samples/speech
> npm run lint


> nodejs-docs-samples-speech@0.0.1 lint /Users/jdobry/nodejs-docs-samples/speech
> samples lint

lint: Linting files in: /Users/jdobry/nodejs-docs-samples/speech
lint: Running: semistandard
lint: Looks good!

> nodejs-docs-samples-speech@0.0.1 test /Users/jdobry/nodejs-docs-samples/speech
> samples test run --cmd ava -- -T 20s --verbose system-test/*.test.js

run: Executing tests in: /Users/jdobry/nodejs-docs-samples/speech
run: Running: ava -T 20s --verbose system-test/quickstart.test.js system-test/recognize.test.js

  ✔ quickstart › should run quickstart (1.6s)
  ✔ recognize › should run streaming recognize (1.9s)
  ✔ recognize › should run sync recognize with word time offset (1.9s)
  ✔ recognize › should run sync recognize (1.9s)
  ✔ recognize › should run sync recognize on a GCS file (2.3s)
  ✔ recognize › should run async recognize on a local file (2.7s)
  ✔ recognize › should run async recognize on a GCS file (2.8s)
  ✖ recognize › should run async recognize on a GCS file with word time offset

  1 test failed [10:10:42]

  recognize › should run async recognize on a GCS file with word time offset
  /Users/jdobry/nodejs-docs-samples/speech/system-test/recognize.test.js:74

   73:   const output = await runAsync(`${cmd} async-gcs-words gs://${bucketName}/${filename}`, cwd);
   74:   t.true(output.includes(`Transcription: ${text}`));
   75:   // Check for word time offsets

  Value is not `true`:

  false

  output.includes(`Transcription: ${text}`)
  => false

  `Transcription: ${text}`
  => 'Transcription: how old is the Brooklyn Bridge'

  text
  => 'how old is the Brooklyn Bridge'

  output
  => `Transcription:  how old is the Brooklyn Bridge␊
  Word: how␊
     0.0 secs - 0.3 secs␊
  Word: old␊
     0.3 secs - 0.6 secs␊
  Word: is␊
     0.6 secs - 0.8 secs␊
  Word: the␊
     0.8 secs - 0.9 secs␊
  Word: Brooklyn␊
     0.9 secs - 1.1 secs␊
  Word: Bridge␊
     1.1 secs - 1.5 secs`

  Test.<anonymous> (system-test/recognize.test.js:74:3)
  step (system-test/recognize.test.js:21:191)

run: Test failed.
npm ERR! Test failed.  See above for more details.
```

**Comment by jerjou** [comment]
Here's what I got:

```sh
$ docker run -it google/nodejs /bin/bash
root@d2d0c841b696:/app# cd
root@d2d0c841b696:~# ls
root@d2d0c841b696:~# npm install -g semistandard
/nodejs/bin/semistandard -> /nodejs/lib/node_modules/semistandard/bin/cmd.js
semistandard@11.0.0 /nodejs/lib/node_modules/semistandard
├── eslint-config-standard-jsx@4.0.1
├── eslint-config-standard@10.2.1
├── eslint-config-semistandard@11.0.0
├── eslint-plugin-standard@3.0.1
├── eslint-plugin-promise@3.5.0
├── standard-engine@7.0.0 (get-stdin@5.0.1, minimist@1.2.0, deglob@2.1.0, pkg-conf@2.0.0)
├── eslint-plugin-node@4.2.3 (object-assign@4.1.1, ignore@3.3.5, semver@5.3.0, minimatch@3.0.4, resolve@1.4.0)
├── eslint-plugin-import@2.2.0 (contains-path@0.1.0, lodash.cond@4.5.2, builtin-modules@1.1.1, doctrine@1.5.0, minimatch@3.0.4, debug@2.6.8, has@1.0.1, pkg-up@1.0.0, eslint-module-utils@2.1.1, eslint-import-res
olver-node@0.2.3)
├── eslint-plugin-react@6.10.3 (doctrine@1.5.0, has@1.0.1, object.assign@4.0.4, jsx-ast-utils@1.4.1, array.prototype.find@2.0.4)
└── eslint@3.19.0 (path-is-inside@1.0.2, strip-bom@3.0.0, imurmurhash@0.1.4, natural-compare@1.4.0, ignore@3.3.5, estraverse@4.2.0, pluralize@1.2.1, strip-json-comments@2.0.1, globals@9.18.0, esutils@2.0.2, esq
uery@1.0.0, progress@1.1.8, text-table@0.2.0, is-resolvable@1.0.0, user-home@2.0.0, babel-code-frame@6.26.0, doctrine@2.0.0, debug@2.6.8, levn@0.3.0, optionator@0.8.2, json-stable-stringify@1.0.1, require-uncac
hed@1.0.3, chalk@1.1.3, glob@7.1.2, mkdirp@0.5.1, concat-stream@1.6.0, inquirer@0.12.0, is-my-json-valid@2.16.1, espree@3.5.0, file-entry-cache@2.0.0, js-yaml@3.9.1, shelljs@0.7.8, table@3.8.3, escope@3.6.0, lo
dash@4.17.4)
root@d2d0c841b696:~# git clone https://github.com/GoogleCloudPlatform/nodejs-docs-samples
Cloning into 'nodejs-docs-samples'...
remote: Counting objects: 8118, done.
remote: Compressing objects: 100% (111/111), done.
remote: Total 8118 (delta 56), reused 61 (delta 33), pack-reused 7974
Receiving objects: 100% (8118/8118), 13.03 MiB | 0 bytes/s, done.
Resolving deltas: 100% (5057/5057), done.
Checking connectivity... done.
root@d2d0c841b696:~# cd nodejs-docs-samples/speech/
root@d2d0c841b696:~/nodejs-docs-samples/speech# git checkout -b speech-allresults origin/speech-allresults
Branch speech-allresults set up to track remote branch speech-allresults from origin.
Switched to a new branch 'speech-allresults'
root@d2d0c841b696:~/nodejs-docs-samples/speech# npm install
-
> grpc@1.4.1 install /root/nodejs-docs-samples/speech/node_modules/@google-cloud/speech/node_modules/google-gax/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library
[grpc] Success: "/root/nodejs-docs-samples/speech/node_modules/@google-cloud/speech/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/grpc_node.node" is installed via remote
node-record-lpcm16@0.3.0 node_modules/node-record-lpcm16
yargs@8.0.2 node_modules/yargs
├── get-caller-file@1.0.2
├── decamelize@1.2.0
├── y18n@3.2.1
├── camelcase@4.1.0
├── which-module@2.0.0
├── set-blocking@2.0.0
├── yargs-parser@7.0.0
├── require-main-filename@1.0.1
├── require-directory@2.1.1
├── string-width@2.1.1 (is-fullwidth-code-point@2.0.0, strip-ansi@4.0.0)
├── cliui@3.2.0 (wrap-ansi@2.1.0, strip-ansi@3.0.1, string-width@1.0.2)
├── os-locale@2.1.0 (mem@1.1.0, lcid@1.0.0, execa@0.7.0)
└── read-pkg-up@2.0.0 (find-up@2.1.0, read-pkg@2.0.0)
@google-cloud/storage@1.2.1 node_modules/@google-cloud/storage
├── arrify@1.0.1
├── string-format-obj@1.1.0
├── hash-stream-validation@0.2.1
├── is@3.2.1
├── extend@3.0.1
├── once@1.4.0 (wrappy@1.0.2)
├── create-error-class@3.0.2 (capture-stack-trace@1.0.0)
├── stream-events@1.0.2 (stubs@3.0.0)
├── mime-types@2.1.16 (mime-db@1.29.0)
├── pumpify@1.3.5 (inherits@2.0.3, pump@1.0.2)
├── concat-stream@1.6.0 (inherits@2.0.3, typedarray@0.0.6, readable-stream@2.3.3)
├── through2@2.0.3 (xtend@4.0.1, readable-stream@2.3.3)
├── duplexify@3.5.1 (inherits@2.0.3, end-of-stream@1.4.0, stream-shift@1.0.0, readable-stream@2.3.3)
├── @google-cloud/common@0.13.5 (array-uniq@1.0.3, methmeth@1.1.0, retry-request@2.0.5, log-driver@1.2.5, ent@2.2.0, modelo@4.2.0, split-array-stream@1.0.3, google-auto-auth@0.7.2, request@2.81.0)
├── gcs-resumable-upload@0.8.1 (buffer-equal@1.0.0, configstore@3.1.1, google-auto-auth@0.7.2, request@2.81.0)
└── async@2.5.0 (lodash@4.17.4)
@google-cloud/speech@0.10.2 node_modules/@google-cloud/speech
├── extend@3.0.1
├── stream-events@1.0.2 (stubs@3.0.0)
├── through2@2.0.3 (xtend@4.0.1, readable-stream@2.3.3)
├── pumpify@1.3.5 (inherits@2.0.3, pump@1.0.2, duplexify@3.5.1)
├── google-proto-files@0.12.1
└── google-gax@0.13.4 (is-stream-ended@0.1.3, process-nextick-args@1.0.7, readable-stream@2.3.3, google-proto-files@0.9.1, google-auto-auth@0.5.4, lodash@4.17.4, grpc@1.4.1)
root@d2d0c841b696:~/nodejs-docs-samples/speech# set -x GCLOUD_PROJECT nodejs-docs-samples
root@d2d0c841b696:~/nodejs-docs-samples/speech# set -x GOOGLE_APPLICATION_CREDENTIALS /jerjou-scratch-extern-ae7207bcf51a.json 
+ set -x GOOGLE_APPLICATION_CREDENTIALS /jerjou-scratch-extern-ae7207bcf51a.json
root@d2d0c841b696:~/nodejs-docs-samples/speech# npm test
+ npm test
> nodejs-docs-samples-speech@0.0.1 pretest /root/nodejs-docs-samples/speech
> npm run lint
> nodejs-docs-samples-speech@0.0.1 lint /root/nodejs-docs-samples/speech
> samples lint
sh: 1: samples: not found
npm ERR! Linux 4.4.0-75-generic
npm ERR! argv "/nodejs/bin/node" "/nodejs/bin/npm" "run" "lint"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! nodejs-docs-samples-speech@0.0.1 lint: `samples lint`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the nodejs-docs-samples-speech@0.0.1 lint script 'samples lint'.
npm ERR! This is most likely a problem with the nodejs-docs-samples-speech package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     samples lint
npm ERR! You can get their info via:
npm ERR!     npm owner ls nodejs-docs-samples-speech
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /root/nodejs-docs-samples/speech/npm-debug.log
npm ERR! Test failed.  See above for more details.
root@d2d0c841b696:~/nodejs-docs-samples/speech# 
```

**Comment by jerjou** [comment]
ah ok. apparently the google/nodejs docker image has problems or something (or is old?). I was able to use the bare `node` docker image to at least get past the lint stage..

**Comment by jerjou** [comment]
Okay. Managed to run the tests... and ... they pass?
Okay, looks like circleci agrees too.

**Comment by jerjou** [comment]
Ugh. Apparently gcr hates me. Any idea why?

**Comment by jerjou** [comment]
Okay. Got gcr to like me again. PTAL

**Pull request merged**
