### PR TITLE
samples(talent): migrate code from googleapis/nodejs-talent

### PR DESCRIPTION
**Pull request by telpirion**
- samples(talent): add Job Search v4 samples (#255)
- fix: flaky sample test two ways (#375)

### CODE REVIEW

**Review by grayside — CHANGES_REQUESTED** [review]
Missing: package.json
Missing: test integration, but possibly there are no tests?

**Comment by kweinmeister** [comment]
+1, we should include tests (see: https://github.com/googleapis/nodejs-talent/blob/main/samples/test/talent.test.js)

Also, need to run the script to create a test workflow (see CONTRIBUTING.md) and include that here, demonstrating that the tests run properly in this new location.

**Comment by telpirion** [comment]
It looks like the tests are just that one test file. I'll add it into this PR.

**Comment by telpirion** [comment]
Nevermind. I'm going to close this PR and start over.

**Pull request closed without merging**
