### PR TITLE
fix(functions): Fix/update GCF Memorystore sample

### PR DESCRIPTION
**Pull request by ericschmidtatwork**
The Node.js Redis client's interface changed in v4 to use Promises by default, so this update addresses that.

This PR also:
* Updates the function definition to use the declarative Functions Framework syntax
* Makes corresponding updates to the unit test
* Adds a link in the README to the tutorial that uses this sample

### CODE REVIEW

**Review by averikitsch — APPROVED** [review]

**Review by averikitsch — CHANGES_REQUESTED** [review]
This needs a workflow file to run the tests. See https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/.github/workflows/functions-slack.yaml for an example

**Comment by ericschmidtatwork** [comment]
@averikitsch Thanks, done!

**Comment by averikitsch** [comment]
Forks don't get access to secrets. I ran the test under my credentials https://github.com/GoogleCloudPlatform/nodejs-docs-samples/actions/runs/3491368815/jobs/5843921346.

**Review by averikitsch — APPROVED** [review]

**Review by ace-n — APPROVED** [review]

**Comment by ace-n** [comment]
Test passed on @akitsch's run; merging.

**Pull request merged**
