### PR TITLE
Fix .blur call to add both parameters

### PR DESCRIPTION
**Pull request by wu4f**
Blur needs radius and sigma.  .blur(16) barely blurs the image.  I believe .blur(0,16) was the intended behavior.

### CODE REVIEW

**Comment by fhinkel** [comment]
Good catch, thanks!

**Comment by fhinkel** [comment]
The linter in `functions/imagemagick` isn't happy. Can you run `npm run lint -- --fix` and push again. Thanks!

**Comment by fhinkel** [comment]
ping @wu4f

**Comment by wu4f** [comment]
Oh..whoops.  Sorry about that.  I missed the previous email.   Committed
the change with the space added after the ','

Thanks!
Wu-chang

**Pull request merged**
