### PR TITLE
Initial commit of sample

### PR DESCRIPTION
**Pull request by gguuss**

### CODE REVIEW

**Comment by gguuss** [comment]
@jmdobry this is the initial push for the API-client based sample I had mentioned.

**Comment by jmdobry** [comment]
Is this ready for review?

**Comment by gguuss** [comment]
@jmdobry I'll do what I can to clean it up tonight for review tomorrow.

**Comment by gguuss** [comment]
@jmdobry Should be a bit better now.

**Comment by jmdobry** [comment]
Remaining TODOs for subsequent PRs:

- [ ] - Switch from Command to Yargs
- [ ] - Turn the two examples into real CLIs
- [ ] - Add tests the exercise the CLIs
- [ ] - Move the IAM script into the device manager example

**Pull request merged**
