### PR TITLE
Add KMS import sample.

### PR DESCRIPTION
**Pull request by bdhess**
Do not submit: likely needs more work, but wanting to run the tests in ci build

### CODE REVIEW

**Comment by pattishin** [comment]
Hi @bdhess! No worries - I just wanted to highlight that we require samples to be added via direct branch against repo rather than from a forked sample. That should help get the current items unblocked.

**Comment by bdhess** [comment]
@pattishin not sure what that means?  I should create a branch in GoogleCloudPlatform/nodejs-docs-samples rather than in my own fork?  Do I have permissions to do that?

**Comment by Sita04** [comment]
@bdhess Yes, that's right. Since Github actions doesn't auth via fork, you'd have to create a branch in this repo and raise a PR against it.

**Comment by pattishin** [comment]
Hi @bdhess, do let us know when this is ready to review.

**Comment by bdhess** [comment]
I think this is ready for review

However I am not able to create a branch in this repo:

```
 ❯ git push origin HEAD:bdhess-import
ERROR: Permission to GoogleCloudPlatform/nodejs-docs-samples.git denied to bdhess.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```

**Comment by pattishin** [comment]
@bdhess Yes, so we do require you to branch directly off of GoogleCloudPlatform/nodejs-docs-samples. Not a forked version due to security restrictions. If you need access for that (we accomplish this on a team basis), please do ping me internally.

**Comment by pattishin** [comment]
@bdhess Bumping this up 👍🏼

**Comment by bdhess** [comment]
Closing in favor of #3574.

**Pull request closed without merging**
