### PR TITLE
pr/5

### PR DESCRIPTION
**Pull request by jmdobry**
Creating repo-local pr of #5 so travis tests can pass.

My manual testing:

- [x] - express
- [x] - geddy
- [x] - grunt
- [x] - hapi
- [x] - koa
- [x] - kraken
- [x] - loopback
- [x] - redis
- [x] - restify
- [x] - sails

Style and licenses:

- [x] - express
- [x] - geddy
- [x] - grunt
- [x] - hapi
- [x] - koa
- [x] - kraken
- [x] - loopback
- [x] - redis
- [x] - restify
- [x] - sails

### CODE REVIEW

**Comment by jmdobry** [comment]
@jonparrott @jsimonweb Do we want everything in this PR to adhere to the rules currently defined in `.jshintrc`?

Also, do we need that Apache 2.0 license header at the top of every file like I've seen in other places?

**Comment by jonparrott** [comment]
1. Up to you.
2. Absolutely. Anything written by a human should have that.

**Comment by jmdobry** [comment]
Sounds good.

**Comment by jmdobry** [comment]
Merged after review.

**Pull request merged**
