### PR TITLE
chore(functions): switch to Node 12

### LINKED ISSUE #1925: functions: update samples to Node 12
GCF Node 12 went beta.

We should update the sample to use Node 12 syntax and update the engine target to Node 12+.

Related:
https://github.com/GoogleCloudPlatform/nodejs-docs-samples/issues/1917

### PR DESCRIPTION
**Pull request by ace-n**
Fixes #1925.

**Please merge for me** once all requested reviewers have signed off. Thanks!

### CODE REVIEW

**Review by grant — APPROVED** [review]

**Review by fhinkel — APPROVED** [review]

**Review by ricalo — APPROVED** [review]

**Comment by fhinkel** [comment]
ping @djmailhot @nnegrey @jsimonweb

**Comment by ace-n** [comment]
@jsimonweb LGTMed offline.

Given that @djmailhot is OOO - @fhinkel should we merge this once @ricalo approves?

**Review by jsimonweb — APPROVED** [review]

**Comment by ricalo** [comment]
> Given that @djmailhot is OOO - @fhinkel should we merge this once @ricalo approves?
I already approved, @ace-n. But thanks for checking!

**Comment by ace-n** [comment]
@ricalo ah my bad, I confused you for @nnegrey (who's since left our team)

@fhinkel please merge this unless you have objections. 🙂

**Pull request merged**
