### PR TITLE
Iot mqtt tests

### PR DESCRIPTION
**Pull request by gguuss**
Adds the same tests from HTTP for MQTT device sample.

### CODE REVIEW

**Comment by gguuss** [comment]
FYI, this is committed atop the HTTP PR.

**Comment by ace-n** [comment]
^ Mind merging that one in first + rebasing this one on top of it?

**Comment by gguuss** [comment]
@ace-n I've merged with master and added the changes you suggested in the HTTP review.

**Comment by gguuss** [comment]
@jmdobry are you around? I think Ace is out for a while.

**Pull request merged**
