### PR TITLE
chore(functions): remove unused signed url sample

### PR DESCRIPTION
**Pull request by ace-n**

### CODE REVIEW

**Review by grant — APPROVED** [review]
We're remembering to remove the tests if there are some, right?

**Comment by ace-n** [comment]
The Node.js tests, yes. (I presume the Kokoro tests would fail if we didn't, anyway.)

**Comment by ace-n** [comment]
@kurtisvg the Cloud SQL GAE tests are failing...is that something you can fix?

(cc @fhinkel in case we should merge as-is instead.)

**Comment by kurtisvg** [comment]
> @kurtisvg the Cloud SQL GAE tests are failing...is that something you can fix?

The samples in `/appengine` are owned by the Serverless team. Our team owns the ones in `/cloudsql`, which appear to all be passing. 

If there are an issue with Cloud SQL tests going forward, please open an issue and assign it to myself or GoogleCloudPlatform/cloud-sql-dpes and we'll prioritize it against our other existing work.

**Comment by ace-n** [comment]
@kurtisvg ah, thanks for clarifying!

@shubha-rajan said we could disable the offending tests for now until they're fixed. Will re-run them.

**Pull request merged**
