### PR TITLE
updating obsolete method for BigQuery

### PR DESCRIPTION
**Pull request by take4mats**
Thank you for providing nice tutorials.
This is quickest proposal to make it work with latest client library.
- Line 339: `table.import(...)` doesn't work and need to use `table.load(...)` instead.
- Line 341: `job` doesn't have `promise()`

### CODE REVIEW

**Comment by fhinkel** [comment]
@take4mats thanks for the fix! Could you sign the CLA? Thank you

**Comment by take4mats** [comment]
@fhinkel sorry for belated reaction... @googlebot I signed it!

**Comment by fhinkel** [comment]
@take4mats so sorry, as @ace-n mentioned, we landed a large change and have merge conflicts now. Do you want to resolve them? Thanks

**Comment by take4mats** [comment]
@fhinkel No, you can discard mine and prioritize the big change. Thank you.

**Pull request closed without merging**
