### PR TITLE
feat: adds tune LLM sample

### PR DESCRIPTION
**Pull request by telpirion**
This PR adds the region tag `aiplatform_model_tuning` for Node.js.

### CODE REVIEW

**Review by kweinmeister — APPROVED** [review]

**Comment by pattishin** [comment]
@telpirion nice! do you mind checking on the `ai-platform-snippets` workflow failure?

**Comment by kweinmeister** [comment]
Looks like it might just be missing "sinon" in `devDependencies`.

**Comment by kweinmeister** [comment]
In logs, failing with:
```
Tune a model
       should prompt-tune an existing model:
     Error: 3 INVALID_ARGUMENT: You do not have permission to act as service_account:
```

FYI @gericdong

**Comment by telpirion** [comment]
For posterity: the GCP project used for Vertex AI (pointed to by `process.env.CAIP_PROJECT_ID`) is not the same as the project used by the rest/most of nodejs-docs-samples. When this test attempted to create a new storage bucket for output, it was using invalid ADC (not using the `process.env.CAIP_PROJECT_ID` service account).

**Comment by pattishin** [comment]
Checking this out more. Investigating that last test failure around the uCAIP service account 🧐

**Comment by gericdong** [comment]
Just removed the public access prevention for the storage bucket to see if this is the cause of the permission issue.

**Comment by gericdong** [comment]
The CI test was aborted because the featurestore test timed out the test run, as message shown below. The CI will be rerun once the featurestore test is stable.

AI platform create featurestore with fixed nodes
Error: The operation was canceled.

**Pull request merged**
