### PR TITLE
refactor: Remove functions_background_synchronous

### PR DESCRIPTION
**Pull request by grant**
Removes `functions_background_synchronous`.
This sample do not show any new feature that is not shown in other samples.
It is also is not a useful sample to duplicate across languages.

Docs: https://cloud.google.com/functions/docs/writing/background#terminating_background_functions
CL: cl/270366828

### CODE REVIEW

**Comment by ace-n** [comment]
Not a bad idea, but can you update [the relevant doc](https://cloud.google.com/functions/docs/writing/background#functions_background_terminate-node8-10) first?

**Comment by grant** [comment]
> Not a bad idea, but can you update [the relevant doc](https://cloud.google.com/functions/docs/writing/background#functions_background_terminate-node8-10) first?

I've created CL 270366828. Note, I'm not able to stage due to updates to Devsite 2.

**Comment by grant** [comment]
The error states:

```
  ✓ should make a promise request (498ms)
  functions_background_synchronous
    1) should return synchronously
    ✓ should throw an error


  2 passing (2s)
  1 failing

  1) functions_background_synchronous
       should return synchronously:
     TypeError: program.helloSynchronous is not a function
      at Context.it (test/index.test.js:73:15)
```

But this has been removed. Not sure what is happening.

**Comment by grant** [comment]
The broken test is completely separate from the changes made in this PR.

```
Internal CI (run/logging-manual) — Tests failed.
```

It's not in the `functions/` directory.

Since this PR is approved and `functions/` test pass, merging.

**Pull request merged**
