### PR TITLE
Added back datastore v1beta3 samples.

### PR DESCRIPTION
**Pull request by jmdobry**
This can be merged to master when Datastore v1beta3 is released.

### CODE REVIEW

**Comment by jmdobry** [comment]
@stephenplusplus Can we get the `nodejs-docs-samples` project whitelisted for v1beta3?

**Comment by stephenplusplus** [comment]
@pcostello

**Comment by stephenplusplus** [comment]
@pcostell

**Comment by pcostell** [comment]
Done.

**Pull request merged**
