### PR TITLE
Fix Node Kokoro tests

### PR DESCRIPTION
**Pull request by ace-n**
~~**Do not merge**~~

### CODE REVIEW

**Comment by steren** [comment]
@fhinkel are you aware that many samples are failing on Node 8? Is this a known fact?

**Comment by ace-n** [comment]
Failures may be a Kokoro problem, not a sample problem. Attempting to debug now...

**Comment by ace-n** [comment]
Looks like all samples pass (locally at least, these tests don't deploy to GAE).

@paulrossman @steren any further work required here?

**Comment by steren** [comment]
Nice! thanks a lot. I had nothing else in mind. 
LGTM to merge

**Comment by crwilcox** [comment]
@ace-n  this lgtm. The failure in billing seems to be a dependency issue that needs resolving though:

```
lint: Linting files in: /tmpfs/src/github/nodejs-docs-samples/functions/billing
lint: Running: semistandard 
/bin/sh: 1: semistandard: not found
lint: Oh no! Linting failed after 0.00400s.
```

**Comment by ace-n** [comment]
Fixing that test will (likely) require switching the base image to Node 8. I'll do that in another PR.

**Pull request merged**
