### PR TITLE
Add samples for Data Catalog lookupEntry

### PR DESCRIPTION
**Pull request by mesmacosta**
Adding samples to Data Catalog lookup_entry, according to #1447

### CODE REVIEW

**Comment by mesmacosta** [comment]
sure @fhinkel, I added it following the convention of the other samples, let me know if i need to do anything else. Thanks

**Comment by fhinkel** [comment]
Awesome, let me configure the CI on our side and run again.

**Comment by fhinkel** [comment]
Looks like there are a few linter problems. Can you ran `npm run lint -- --fix` in the parent directory please. Thanks

```
/tmpfs/src/github/nodejs-docs-samples/datacatalog/cloud-client/lookupEntry.js
   1:4   error    Delete `·`                                                                    prettier/prettier
  25:1   warning  Expected a function expression                                                func-style
  29:1   error    Delete `⏎`                                                                    prettier/prettier
  34:10  error    Replace `·DataCatalogClient·` with `DataCatalogClient`                        prettier/prettier
  37:3   warning  Expected a function expression                                                func-style
  38:5   warning  Unexpected 'todo' comment                                                     no-warning-comments
  42:22  error    Replace `·linkedResource:·resourceName·` with `linkedResource:·resourceName`  prettier/prettier
  47:12  warning  Prefer await to then()                                                        promise/prefer-await-to-then
  47:30  error    Replace `·console.log(response)` with `⏎····console.log(response);⏎·`         prettier/prettier
/tmpfs/src/github/nodejs-docs-samples/datacatalog/cloud-client/system-test/datacatalog.test.js
   1:4    error  Delete `·`  prettier/prettier
  33:105  error  Insert `;`  prettier/prettier
  35:4    error  Insert `⏎`  prettier/prettier
```

**Comment by mesmacosta** [comment]
I had to also fix some lint issue on the test file. Thanks

**Pull request merged**
