### PR TITLE
fix(functions/imagemagick): drop dependency on request

### PR DESCRIPTION
**Pull request by JustinBeckwith**

### CODE REVIEW

**Review by ace-n — CHANGES_REQUESTED** [review]
Two concerns I have:
1) Tests are failing. 🙂
2) ~While I'm not opposed to refactors like this ^, we'll have to either a) **apply them to all `functions` samples** or b) **file issues as reminders**.~ Looks like #2263 is related to this.

~_^: this is more about the `wait-port` refactor than the `request` --> `gaxios` one._~

**Comment by JustinBeckwith** [comment]
@ace-n at a glance, it looks like the failing tests are largely unrelated to the code I touched.  I assume these are flakes, since the functions/imagemagick tests are passing?

**Comment by JustinBeckwith** [comment]
Oh and on the other concern - I am slowly removing `request` from all the samples since it's deprecated.  The `wait-port` changes are coming at the same time, because as far as I can tell the retry logic used in retry-request was largely there to deal with ambiguity on if functions framework was ready yet.  The `wait-port` pattern is more clear, and negates the need for retries in most of these cases.

**Comment by ace-n** [comment]
Yeah, looks like they were flakes. (It may have been because the system test deployments don't use UUIDs, and collided with each other. This is somewhat hard to fix, per b/191301443 - but maybe it's worth doing since this isn't the first time it happened?)

**Comment by JustinBeckwith** [comment]
@ace-n I think the real answer here is to only run tests for samples that changed during a PR.  I have a little experiment rolling here with Cloud Build (see the healthcare dicom test), but it's going to take a bit of time to work out the details.  In the interim...  is there anything else you want me to do with this PR?

**Review by ace-n — APPROVED** [review]
If `functions/imagemagick` is passing, I think we can merge this. :+1:

**Pull request merged**
