### PR TITLE
Memorystore GCE : Replace GCS_APP_LOCATION with GCS_BUCKET_NAME

### PR DESCRIPTION
**Pull request by jabubake**

### CODE REVIEW

**Comment by jabubake** [comment]
@fhinkel : the failures don't seem related to my PR. What's the best path forward ?

**Comment by kurtisvg** [comment]
@fhinkel What can we do to get this merged? It is blocking a CL to update the documentation.

**Comment by fhinkel** [comment]
So sorry, completely missed this. Looking at it now

**Comment by fhinkel** [comment]
@ace-n , please merge this once you've fixed the test config. Thanks!

**Pull request merged**
