### PR TITLE
feat: Create Data Catalog search sample

### PR DESCRIPTION
**Pull request by mesmacosta**
Currently we have inline search samples at:
https://cloud.google.com/data-catalog/docs/how-to/search#data-catalog-how-to-search-nodejs

Sending this PR so tech writer can point the samples to the nodejs-docs-samples github.

Need help at setting an environment variable with the test project Org ID at:
`.kokoro/datacatalog.cfg `
Could one of the reviewers provide the org id?

### CODE REVIEW

**Comment by mesmacosta** [comment]
Hi @fhinkel 

Could you help providing the value for the environment variable - Organization ID for the test Project at:
.kokoro/datacatalog.cfg
?

I didn't find any other samples using the Org ID.

**Comment by fhinkel** [comment]
As far as I can tell we don't have an org set up.

**Comment by mesmacosta** [comment]
I will remove the org_id sample from this PR then, and keep just the sample that uses the project scope, I will try to find out internaly if there's a way to set up a test org id.

**Comment by fhinkel** [comment]
Can you use the same project as this test? https://github.com/googleapis/nodejs-security-center/blob/e50061a5f834a356b0221ff01d8de4ed02089260/.kokoro/samples-test.sh#L24

**Comment by mesmacosta** [comment]
Thanks! I will test it out.

**Comment by mesmacosta** [comment]
@fhinkel 
Are you able to whitelist those environment variables?
"
GCLOUD_ORGANIZATION="1081635000895" (No matching key in allowed env vars)
GCLOUD_ORGANIZATION_PROJECT="project-a" (No matching key in allowed env vars)
"

**Comment by mesmacosta** [comment]
ping @fhinkel

**Comment by fhinkel** [comment]
Whitelisted those variables.

**Pull request closed without merging**
