### PR TITLE
slackbot example update to reflect package and api changes

### PR DESCRIPTION
**Pull request by amygdala**

### CODE REVIEW

**Comment by amygdala** [comment]
hmm, sorry... can someone remind me of the node linter I should use?
Might also need some help deciphering some of the other test errors.

**Comment by fhinkel** [comment]
Thanks! I ran the linter and pushed (`npm run lint` and `npm run lint -- --fix`). Do we have a Slack token we can use for the tests?

**Comment by amygdala** [comment]
I'm not sure if we ever had one.  Tim -- you have also created some slackbot examples... do you know if we have a test token?  If not, I can generate one. @tswast

**Comment by tswast** [comment]
I created https://clouddpes.slack.com/ a while back to test Slack samples. I've still got a few apps at https://api.slack.com/apps

I'm not sure how to get a Slack API token anymore. I think they've moved to more of an OAuth2-based flow as their recommended auth mechanism.

**Comment by amygdala** [comment]
It looks like it's still possible to get this kind of 'bot' token, IIUC: https://api.slack.com/docs/token-types#bot
Would you have a token you'd be willing to use for testing? (I currently just have one, so I don't want to repurpose it).  @tswast 
If not, I can create another one. (and maybe connect its app to that clouddpes slack?)

**Comment by fhinkel** [comment]
ping @amygdala Can you have a look at the merge conflict. Thanks!

**Comment by fhinkel** [comment]
ping @amygdala

**Comment by amygdala** [comment]
ooops, sorry.  This had popped off my stack.  Will do!

**Comment by amygdala** [comment]
(ughh, I need to figure out how to lint with node.  Clearly more is needed in terms of setup than I have installed)

**Comment by amygdala** [comment]
I'm rethinking: I'm having trouble finding the bandwidth to deal with this right now, and it's kind of an orphaned example anyway-- how about I just move it into one of my own repos and relink the blog post?

**Comment by amygdala** [comment]
Getting back to this after the holidays.  I'm closing this PR, and will just move the code into one of my own repos.

**Pull request closed without merging**
