### PR TITLE
added opencensus sample and test

### PR DESCRIPTION
**Pull request by yuriatgoogle**
Adding an OpenCensus sample for creating SLI metrics to be used in product documentation. 
proposed documentation is in cl/343542215

### CODE REVIEW

**Comment by yuriatgoogle** [comment]
I don't think those checks are failing because of something I did?

**Review by fhinkel — CHANGES_REQUESTED** [review]
Thanks! Can you please add the kokoro configs (both in .kokoro here and internally) so we see those tests actually run on CI.

**Comment by yuriatgoogle** [comment]
@fhinkel I would very much like to.... but I honestly couldn't make much sense of how to do that.  Is there any way to get some help with that part?

**Comment by fhinkel** [comment]
Sent you a message via chat.

**Comment by yuriatgoogle** [comment]
@fhinkel I've added the internal kokoro configs (thanks for approving that!) and added myself to CODEOWNERS with the last push.  I don't think I need to do anything in .kokoro here?  PTAnotherL?  Thank you very much in advance.

**Comment by fhinkel** [comment]
You need to add a config file for `monitoring/opencensus/opencensus.cfg` in https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/master/.kokoro. Then you should see "Internal CI (monitoring/opencensus)"  as the 60th CI test on this PR.

**Comment by yuriatgoogle** [comment]
> You need to add a config file for `monitoring/opencensus/opencensus.cfg` in https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/master/.kokoro. Then you should see "Internal CI (monitoring/opencensus)" as the 60th CI test on this PR.

I've done that, though I'm not sure my file is correct.....

**Comment by fhinkel** [comment]
Awesome, your tests ran! GitHub shows them as green, but when you look at the logs, they didn't get very far: https://source.cloud.google.com/results/invocations/03bfe6a8-1df6-4bfb-b444-3c353c885ed7/targets/cloud-devrel%2Fnodejs-docs-samples%2Fpresubmit%2Fmonitoring%2Fopencensus%2Fopencensus/log

Can you look into the tests and how you call them, so failures are reported as failures.

**Comment by yuriatgoogle** [comment]
> Awesome, your tests ran! GitHub shows them as green, but when you look at the logs, they didn't get very far: https://source.cloud.google.com/results/invocations/03bfe6a8-1df6-4bfb-b444-3c353c885ed7/targets/cloud-devrel%2Fnodejs-docs-samples%2Fpresubmit%2Fmonitoring%2Fopencensus%2Fopencensus/log
> 
> Can you look into the tests and how you call them, so failures are reported as failures.

There's a problem in that log, but it's not happening in my code:
```
> opencensus-samples@0.0.1 test /tmpfs/src/github/nodejs-docs-samples/opencensus
> mocha -- system-test/*.test.js --timeout=5000 --exit

/tmpfs/src/github/nodejs-docs-samples/opencensus/metrics-quickstart.js:58
  throw Error('Unable to proceed without a Project ID');
  ^
```
My contribution is in /monitoring/opencensus.  The code in /opencensus was already there, so I think something else is going on.

**Comment by yuriatgoogle** [comment]
@fhinkel everything finally works - PTAnotherL?  And thank you so much for your help!

**Review by fhinkel — APPROVED** [review]

**Comment by yuriatgoogle** [comment]
@fhinkel With apologies for nagging - can you please approve and merge?  Thank you very much in advance.

**Review by fhinkel — COMMENTED** [review]
lgtm

**Pull request merged**
