### PR TITLE
secret manager: add example rotation cloud function

### PR DESCRIPTION
**Pull request by tam7t**
Add new sample for Secret Manager: https://cloud.google.com/secret-manager/docs/how-to

Demonstrate using a cloud function triggered through pub/sub from cloud scheduler to rotate a secret on a pre-defined interval.

### CODE REVIEW

**Review by ace-n — CHANGES_REQUESTED** [review]
Can we move this out of the `functions` folder and into its own separate folder? (e.g. `secret-manager/functions`)

_Context: the `functions` folder is reserved for samples used in `cloud.google.com/functions`._

**Comment by tam7t** [comment]
> Can we move this out of the `functions` folder and into its own separate folder? (e.g. `secret-manager/functions`)
> 
> _Context: the `functions` folder is reserved for samples used in `cloud.google.com/functions`._

Sure thing, actually as I look into it more maybe this belongs in the client repo: https://github.com/googleapis/nodejs-secret-manager

**Comment by ace-n** [comment]
@tam7t I'll leave that call to @bcoe and @fhinkel 🙂

**Comment by fhinkel** [comment]
@tam7t Yes, this definitely belongs in the client library repo. Thanks!

**Pull request closed without merging**
