### PR TITLE
Add --runtime argument to gcloud deploy in README.

### PR DESCRIPTION
**Pull request by emilyaherbert**
gcloud requires a `--runtime` argument when deploying new functions, otherwise the user sees:

`ERROR: (gcloud.functions.deploy) Missing required argument [runtime]: Flag `--runtime` is required for new functions.`

This addition is consistent with the tutorial (https://cloud.google.com/functions/docs/tutorials/http).

### CODE REVIEW

**Comment by emilyaherbert** [comment]
@googlebot I signed it!

**Comment by fhinkel** [comment]
👋 @emilyaherbert thanks for opening a pull request. @ace-n Could you have a look please. Thanks.

**Comment by ace-n** [comment]
@labtopia what are your thoughts on this? (We'd have to keep this file up to date.)

@emilyaherbert thanks for the PR! If @labtopia is in favor of this change, would you mind updating the [other files listed here](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/search?q=%22gcloud+functions+deploy%22&unscoped_q=%22gcloud+functions+deploy%22) as well? 🙂

cc @grant as FYI, too.

**Comment by labtopia** [comment]
The README is inaccurate as is, so I'm in favor of fixing it. The problem with listing a specific runtime flag is that they can quickly go out of date. If you want to future-proof it, you could put a variable there instead of a hard-coded value. See what we did here:

https://cloud.google.com/functions/docs/deploying/filesystem#deploy_using_the_gcloud_tool

In the table below, we also link to the gcloud reference for the complete list of valid values for --runtime. You might want to do something like that.

**Comment by grant** [comment]
Changing all `gcloud functions deploy` commands in this PR would be great. We should update all READMEs even if they are outdated.

**Comment by emilyaherbert** [comment]
Cool beans, I'll work on this PR!

**Comment by emilyaherbert** [comment]
Updated!

**Comment by ace-n** [comment]
@emilyaherbert Thanks for updating the other files!

@labtopia would it be better to use explicit runtime versions here, given that GitHub docs are usually more focused on "getting things working" than a full conceptual explanation?

**Comment by labtopia** [comment]
>
@labtopia would it be better to use explicit runtime versions here, given that GitHub docs are usually more focused on "getting things working" than a full conceptual explanation?
>

It's a tradeoff. You know this audience better than I do. Specifying explicit runtimes is fine; it just means the docs will go out of date more frequently, and users won't necessarily know where to look for more info when that happens.

**Comment by ace-n** [comment]
OK, got it.

LGTM; @grant I assume you're cool with explicit version names?

**Pull request merged**
