### PR TITLE
Added integration tests to check that samples run. Closes #20.

### LINKED ISSUE #20: Add integration tests that check that samples run

### PR DESCRIPTION
**Pull request by jmdobry**

### CODE REVIEW

**Comment by jmdobry** [comment]
@jonparrott Can you review?

**Comment by jonparrott** [comment]
Yes, in the future, just assign it to me. :)

**Comment by jonparrott** [comment]
Small nit: I don't like commit messages that are just "Closes #20". Please describe what you did to fix the bug, etc.

**Comment by jonparrott** [comment]
LGTM.

**Pull request merged**
