### PR TITLE
Actions tasks

### PR DESCRIPTION
**Pull request by NicholaiMadias**
Node pull test

### CODE REVIEW

**Review by ricalo — APPROVED** [review]
LGTM from the speech-to-speech sample perspective.

**Comment by sofisl** [comment]
Hi @NicholaiMadias, would you mind sharing a 1-pager or design on these changes to the repo? And, furthermore, we'd need to split out these changes into various PRs, seems like lots of things going on at once.

**Comment by ace-n** [comment]
I suspect this was a "merge gone wrong", @NicholaiMadias try **recreating the PR on fresh branch**?

**Comment by CollabNexus** [comment]
This was a test which was not meant to be deployed.  Please cancel the pending workflows.  I found all your responses and feedback insightful.  Thank you

**Pull request closed without merging**
