### PR TITLE
Initial Cloud Functions auth samples.

### PR DESCRIPTION
**Pull request by jmdobry**

### CODE REVIEW

**Comment by jmdobry** [comment]
@jasonpolites PTAL

These cover just two use case dealing with OAuth 2 + Google APIs + Cloud Functions. They both involve direct access by end users. One stores the access token in the user's cookie, the other stores the access token in Cloud Datastore. I plan to add more samples for different use cases.

**Comment by VikramTiwari** [comment]
I am working on one related to SMS auth for twilio. Not sure if I should open a PR for that.

It was for https://github.com/GoogleCloudPlatform/community/issues/159
and the code is here: https://github.com/VikramTiwari/nodejs-examples/tree/sms-autentication-twilio-gcf/sms-authentication-twilio-gcf

**Comment by jmdobry** [comment]
@VikramTiwari I would continue with your plan to submit a PR to GoogleCloudPlatform/community to solve GoogleCloudPlatform/community#159, publishing your tutorial on the community site would be awesome

**Comment by jasonpolites** [comment]
@jmdobry It looks like we have a lot of boiler-plate oAuth code in there.  Is it worth separating this?  So we'd have a function which just assumed a valid oAuth access token in scope, and a separate set of functions to do generic oAuth.  I worry that "calling Google APIs" ends up looking very complicated

**Comment by jmdobry** [comment]
This is the same boilerplate oAuth code that would need to be used in any Node.js app to call Google oAuth APIs that have user-owned resources. None of the complexity is due to it being on Cloud Functions. 

We could vastly simplify the samples by relying on say, Firebase Google oAuth, which does all of this boilerplate for you. Then the Cloud Function could just get the access_token from Firebase in order to do its thing.

**Comment by jasonpolites** [comment]
Yeah that's what I'm suggesting.  Not *necessarily* Firebase Auth (although that would be fine) but just separating the boiler-plate oAuth dance from the actual API call.  Perhaps also an example using Auth0.  We can *also* do a Cloud Function that demonstrates how to do oAuth

**Comment by jmdobry** [comment]
Yeah, I was getting to those, just started with these.

**Comment by fhinkel** [comment]
@jmdobry Can we close this?

**Pull request closed without merging**
