### PR TITLE
fix: Remove unused parameter

### PR DESCRIPTION
**Pull request by leahecole**

### CODE REVIEW

**Comment by leahecole** [comment]
Not sure why this run/pubsub is failing - I haven't touched it, but I'll see how the other CI stuff turns out.

**Comment by leahecole** [comment]
@fhinkel, @ace-n , @JustinBeckwith , I see that functions/tokenservice and run/pubsub have failed on some other recent PRs. Is this something I need to fix, or something with kokoro?

**Comment by fhinkel** [comment]
:wave: Thanks! 

The failing tests are for PRs that haven't landed yet. That's why they're not required either. Nothing to do with your PR. Sorry for the confusion.

**Comment by leahecole** [comment]
No worries! The perfectionist in me just goes into mild panic when I see that red. Thanks for the review + approval Franzi! :)

**Pull request merged**
