### PR TITLE
Refactor tests and update google-auth-library source link in README

### PR DESCRIPTION
**Pull request by santhoshvaddi**
Refactored functions/tokenservice tests, As requested in #1255
Node 6 --> Node 8 (+ ESLint passing)
Emulator --> Functions Frameworks

### CODE REVIEW

**Comment by grant** [comment]
Hi @santhoshvaddi, Can you please add a description to the PR and let us know what issue this PR is trying to solve?

**Comment by ace-n** [comment]
Also - this is a *lot* of commits. I suspect this needs to be rebased on `master`:

```sh
git checkout refactorTests
git pull --rebase origin master
git push fork refactorTests-2  # Replace 'fork' with your fork's remote name
```

Once you do that, confirm the changes are correct. You can then:
a) create a new PR with these changes, and close this one _(recommended)_, *or*
b) `git push fork refactorTests --force` - note that *this will delete the commits you've pushed to this branch*

Feel free to ping me or @fhinkel if you have further questions about this. 🙂

**Comment by fhinkel** [comment]
No need to close this PR an rebase. I just need to make sure to delete all the comments from the commit message when I merge the PR, that's no problem.

**Comment by fhinkel** [comment]
For some reason the `tokenservice` tests are not picked up by Kokoro. Let me check the internal config.

**Comment by fhinkel** [comment]
Ok, got your tests to run.

**Comment by santhoshvaddi** [comment]
Hi @fhinkel functions/tokenservice tests are passing and as you have suggested in above, I've removed .eslintrc.json file from tokenservice and using the one which we have in the parent folder. Please review and let me know if you have any questions. thanks

**Pull request merged**
