### PR TITLE
feat(auth): samples for auth

### PR DESCRIPTION
**Pull request by FrodoTheTrue**

### CODE REVIEW

**Review by danielbankhead — APPROVED** [review]

**Comment by grayside** [comment]
Is this PR migrating samples from https://github.com/googleapis/google-auth-library-nodejs/tree/main/samples? If so could we follow the revised process to keep the Git commit history?

**Comment by rsamborski** [comment]
@Shnatsel Can you PTAL and get this merged?
@Sita04 can provide more context

**Review by ace-n — CHANGES_REQUESTED** [review]
Highlighting @grayside's [comment](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/2759#issuecomment-1306403855):

> Is this PR migrating samples from https://github.com/googleapis/google-auth-library-nodejs/tree/main/samples? If so could we follow the revised process to keep the Git commit history?

@FrodoTheTrue it's probably easiest to close this PR and create a new one.

**Feel free to DM me (internally) or ask in the (internal) migration chat channel** if any of this is unclear! 😃

**Comment by Shnatsel** [comment]
The samples have instead been added to the client library repository. Since the client library is not automatically generated, there are currently no plans to move the samples to nodejs-docs-samples. Closing.

**Pull request closed without merging**
