### PR TITLE
Fix URL for GCS fuse example.

### PR DESCRIPTION
**Pull request by jeremiele**
The URL for packages.cloud.google.com should be https instead of http.

## Description

Fixes #<ISSUE-NUMBER>

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist
- [ ] I have followed guidelines from [CONTRIBUTING.MD](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/CONTRIBUTING.md) and [Samples Style Guide](https://googlecloudplatform.github.io/samples-style-guide/)
- [ ] **Tests** pass:   `npm test` (see [Testing](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/CONTRIBUTING.md#run-the-tests-for-a-single-sample))
- [ ] **Lint** pass:   `npm run lint` (see [Style](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/CONTRIBUTING.md#style))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] This pull request is from a branch created directly off of `GoogleCloudPlatform/nodejs-docs-samples`. Not a fork.
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new sample directory, and I created [GitHub Actions workflow](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/CONTRIBUTING.md#adding-new-samples) for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample
- [ ] Please **merge** this PR for me once it is approved

### CODE REVIEW

**Review by glasnt — APPROVED** [review]

**Comment by jeremiele** [comment]
Hi, folks!

Is there something we can do to unblock this change?
People are getting confused and are failing to properly set up GCS fuse for Cloud Run due to this typo.

Thanks a lot for your help!

**Comment by pattishin** [comment]
Hi @jeremiele - thank you for your sample! I see the blocked item is `run-filesystem/test` workflow. We require samples to be added via direct branch against repo rather than from a forked sample. That should help you get unblocked.

**Comment by ashmeenkaur** [comment]
Hi @pattishin,

This is a high-priority issue as the GCSFuse team is receiving a lot of alerts related to it (Ref: https://github.com/GoogleCloudPlatform/gcsfuse/issues/1424).

I attempted to raise a pull request via a direct branch, but I do not have permission to do so. Could one of the maintainers please prioritize this?

Thank you,
Ashmeen

**Comment by jeremiele** [comment]
I was given access and created a new PR here: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/3544

**Comment by pattishin** [comment]
Closing in favor of non-forked PR https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/3544.

**Pull request closed without merging**
