### PR TITLE
chore(GAE flex): rm unused SQL samples

### PR DESCRIPTION
**Pull request by ace-n**
@qchong please LGTM too, thanks!

(FYI @fhinkel: please wait until everyone LGTMs before merging, unless you know for sure these samples are no longer used.)

### CODE REVIEW

**Comment by ace-n** [comment]
@fhinkel once this is approved, I'll go ahead and remove the appropriate test triggers internally.

**Comment by qchong** [comment]
LGTM

**Review by fhinkel — APPROVED** [review]

**Comment by ace-n** [comment]
I'll merge this once cl/353765199 is submitted.

**Review by engelke — APPROVED** [review]

**Comment by qchong** [comment]
LGTM

**Pull request merged**
