### PR TITLE
chore(functions): Move to Node 16 (+ fix flaky tests)

### PR DESCRIPTION
**Pull request by ace-n**
~**DO NOT MERGE** until the Node 16 runtime is GA.~

### CODE REVIEW

**Review by averikitsch — APPROVED** [review]

**Comment by ace-n** [comment]
Looks like this image doesn't exist. @sofisl is that something you and @JustinBeckwith can fix?

**Review by sofisl — APPROVED** [review]

**Comment by bcoe** [comment]
@ace-n @sofisl you just need to create a CL here:

https://github.com/googleapis/testing-infra-docker/tree/main/node

Which adds a line to cloudbuild.yaml to build a node-16 directory, and creates a new node-16 directory, using node-14 as a starting point. It should just be a matter of switching the tag on the Docker container.

**Comment by ace-n** [comment]
PR [here](https://github.com/googleapis/testing-infra-docker/pull/181).

**Comment by bcoe** [comment]
@ace-n this update looks reasonable to me, but there seems to be a failing assertion:

`Error: Promise rejected with no or falsy reason`.

**Comment by matthewrobertson** [comment]
nodejs16 is GA on GCF now.

**Comment by ace-n** [comment]
@matthewrobertson I'd like to merge this, but some of the `functions` tests are failing for an unknown reason.

(My best guess is flakiness in the functions frameworks, but it's very hard to know without an error message.)

**Pull request merged**
