### PR TITLE
refactor(appengine-pubsub):ava to mocha

### PR DESCRIPTION
**Pull request by nareshqlogic**
Tracking issue: Convert tests from ava to mocha [#1080](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/issues/1080) (it's a good idea to open an issue first for discussion)

### CODE REVIEW

**Comment by nareshqlogic** [comment]
Hi @fhinkel ,
Regarding **`Node 10 (appengine/pubsub) — Tests failed**.`
From below detail I can see that there is no test cases fail occurred except 'ERROR: Aborting VM command due to timeout of 10800 seconds' . Let me know your view on it.

App listening on port 8080
Press Ctrl+C to quit.
  ✓ should send a message to Pub/Sub (417ms)
  ✓ should receive incoming Pub/Sub messages
  ✓ should check for verification token on incoming Pub/Sub messages
  ✓ should list sent Pub/Sub messages (245ms)
  4 passing (677ms)
ERROR: Aborting VM command due to timeout of 10800 seconds

**Comment by fhinkel** [comment]
That was probably unrelated. Let's try again.

**Comment by fhinkel** [comment]
Pub sub tests are consistently failing. Please have a look at the failing tests.

**Comment by fhinkel** [comment]
ping @nareshqlogic

**Comment by AVaksman** [comment]
@fhinkel Please add kokoro:run (as I am unable) to see the log of why the tests are failing.

**Comment by AVaksman** [comment]
Closing this in favor of #1225

**Pull request closed without merging**
