### PR TITLE
chore: manually updating puppeteer and google-github-actions/auth action to v1.1.1 from forked renovate

### PR DESCRIPTION
**Pull request by pattishin**
## Description
Origin PRs: 
- https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/3206
- https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/3197

Screenshot 2023-05-10 at 4 15 36 PM

Last sentence in error above from PR 3206 , `google-github-actions/auth` seems to error out if job is initiated via forked version. Updating this manually.

## Checklist
- [x] I have followed guidelines from [CONTRIBUTING.MD](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/CONTRIBUTING.md) and [Samples Style Guide](https://googlecloudplatform.github.io/samples-style-guide/)
- [ ] **Tests** pass:   `npm test` (see [Testing](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/CONTRIBUTING.md#run-the-tests-for-a-single-sample))
- [x] **Lint** pass:   `npm run lint` (see [Style](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/CONTRIBUTING.md#style))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new sample directory, and I created [GitHub Actions workflow](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/CONTRIBUTING.md#adding-new-samples) for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample
- [x] Please **merge** this PR for me once it is approved

### CODE REVIEW

**Comment by pattishin** [comment]
Looking into `dialogflow-cx` test failure.

**Comment by kweinmeister** [comment]
Hi @pattishin , thanks for taking care of this!

Just FYI, the way CI is currently configured, we can ignore these `pull_request` failures *if* the matching `pull_request_target` is passing.

The `pull_request_target` actually does setup permissions properly on forks. However, we should manually inspect any forked PRs for security reasons. If it looks good, we can then apply the `actions: force run` label to trigger the PR target check.

We have an open issue #2891 filed to cleanup this workflow.

**Comment by pattishin** [comment]
Thanks @kweinmeister! Checking it out 👍🏼

**Pull request merged**
