### PR TITLE
chore(eventarc): update region tags

### PR DESCRIPTION
**Pull request by grant**
Updates region tags to use `audit_storage`, not `gcs`.

These aren't in the docs, please merge this when approved.

### CODE REVIEW

**Review by ace-n — APPROVED** [review]

**Comment by grant** [comment]
@ace-n Can you merge this?

**Comment by ace-n** [comment]
We should probably fix the tests first. I'm working on debugging `functions/helloworld`; @grayside can you investigate `run/logging-manual`?

**Comment by grant** [comment]
> We should probably fix the tests first (in other PRs). I'm working on debugging `functions/helloworld`; @grayside can you investigate `run/logging-manual`?

Sorry, this PR is unrelated to those PRs and is urgent as there are many other PRs related to this. Can you consider merging this without those unrelated fixes?

**Comment by ace-n** [comment]
OK, I'll mark those tests as un-required for now and create followup issues.

**Pull request merged**
