### PR TITLE
Updated samples for using Cloud SQL with App Engine.

### PR DESCRIPTION
**Pull request by michaelawyu**
Kokoro tests for new samples will not be available until CL 219583668 is merged.
Kokoro tests for existing samples are expected to fail until CL 219583668 is merged (file structure changed).

### CODE REVIEW

**Comment by fhinkel** [comment]
Please only merge if you have time to follow through with the Kokoro changes. Please send an email to @SurferJeffAtGoogle with the list of which jobs got added and which got removed so we can keep our build board up to date.

**Comment by steren** [comment]
ping?

**Comment by fhinkel** [comment]
ping @michaelawyu

**Comment by fhinkel** [comment]
Another ping @michaelawyu

**Comment by fhinkel** [comment]
Closed due to inactivity. Please reopen if needed.

**Pull request closed without merging**
