### PR TITLE
chore: delete samples for talent API

### PR DESCRIPTION
**Pull request by fhinkel**
Samples have moved to
https://github.com/googleapis/nodejs-talent/tree/master/samples/snippet

Fixes: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/issues/1803
Fixes: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/issues/2103

I couldn't find any uses of these samples in our docs.

### CODE REVIEW

**Review by JustinBeckwith — APPROVED** [review]

**Review by JustinBeckwith — CHANGES_REQUESTED** [review]
Flagging this until the snippet bot warning is checked out

**Comment by fhinkel** [comment]
internally: cl/346483900

**Comment by tmatsuo** [comment]
@fhinkel 

When the internal CL lands, the drift database will be updated. Then their cron job will dump the json file for snippet-bot shortly (I think they run it every 5 minutes or so). 

After that point, you can check the `Refresh this comment` checkbox for refreshing the comment from snippet-bot.

Let me know if the bot still warns.

**Comment by tmatsuo** [comment]
@fhinkel It looks like the internal CL landed, so I'm going to check the refresh checkbox.

**Comment by tmatsuo** [comment]
@fhinkel The number went down from 20 to 18.

I think we need to publish the devsite docs for actually updating the database and the published web page.

**Comment by fhinkel** [comment]
@tmatsuo Thanks. Let me run another refresh. The devsite docs are published, see e.g. https://cloud.google.com/talent-solution/job-search/docs/samples/job-search-histogram-search-core

**Comment by tmatsuo** [comment]
@fhinkel It seems like the drift team's data pipeline is delayed. Internal reference b/175210192

Other than that, many devsite pages are still referring to nodejs-docs-samples.

**Comment by fhinkel** [comment]
I'm wondering if we run into problems because the majority of the reported pages are generated by sample-browser.

**Comment by fhinkel** [comment]
@JustinBeckwith The bot found a few legitimate issues and I updated those. The remaining issues are the usages that `sample-browser` generates. They'll disappear when the samples get deleted. @tmatsuo will make that change to the bot, but for now we should ignore the warning.

**Review by JustinBeckwith — APPROVED** [review]
Just please check in with @tmatsuo that he doesn't need this to verify fixes from DRIFT :)

**Pull request merged**
