### PR TITLE
Update index.js for node.js 8+

### PR DESCRIPTION
**Pull request by nbards**
Changes per https://cloud.google.com/functions/docs/migrating/nodejs-runtimes

### CODE REVIEW

**Comment by fhinkel** [comment]
@ace-n Could you have a look. Thanks

**Comment by ace-n** [comment]
@nbards can you do the following?
1. Sign the CLA
2. Update the comments above the method (to match the new parameters)

Once those are done, I can review this in more detail. Thanks!

**Comment by sdenef-adeo** [comment]
Maybe you can close this PR as it is resolved by #1335

**Comment by ace-n** [comment]
Thanks for the ping @sdenef-adeo - will close this as it's obsolete.

**Pull request closed without merging**
