### PR TITLE
Update sample to include an example of gRPC HTTP/JSON transcoding setup.

### PR DESCRIPTION
**Pull request by kryzthov**
- Add `http_helloworld.proto` gRPC definition with HTTP transcoding.
 - Add `http_deployment.yaml` kubernetes deployment with HTTP1.1 port
   enabled for transcoding.
 - Update README accordingly.
 - Update README with long-flags everywhere.

### CODE REVIEW

**Comment by kryzthov** [comment]
@navinger Could you take a look?

**Comment by navinger** [comment]
The readme still has the old gcloud command. The new command is: 
gcloud endpoints services deploy

**Comment by kryzthov** [comment]
Good catch, fixed!

**Comment by navinger** [comment]
The long options for the Docker run and ESP options look good.

**Comment by navinger** [comment]
LGTM for stuff not related to gRPC!!

**Comment by kryzthov** [comment]
@jmdobry Hey Jason, would you be able to take a look whenever you have a chance? Thanks!

**Pull request merged**
