### PR TITLE
Make slack example to work with newer version of googlapis

### PR DESCRIPTION
**Pull request by jingweno**
Make slack example to work with newer version of googlapis

### CODE REVIEW

**Comment by fhinkel** [comment]
This broke the slack tests: 
```
> nodejs-docs-samples-functions-slack@0.0.1 test /tmpfs/src/github/nodejs-docs-samples/functions/slack
> ava -T 20s --verbose test/*.test.js


  ✖ Send fails if not a POST request Rejected promise returned by test
  ✖ Throws if invalid slack token Rejected promise returned by test
  ✖ Handles search error Rejected promise returned by test
  ✖ Makes search request, receives empty results Rejected promise returned by test
  ✖ Makes search request, receives non-empty results Rejected promise returned by test
  ✖ Makes search request, receives non-empty results but partial data Rejected promise returned by test

  6 tests failed

  Send fails if not a POST request

  /tmpfs/src/github/nodejs-docs-samples/functions/slack/index.js:23

   22: // Get a reference to the Knowledge Graph Search component
   23: const kgsearch = google.kgsearch('v1');                   
   24: // [END functions_slack_setup]                            

  Rejected promise returned by test. Reason:

  TypeError {
    message: 'Cannot read property \'kgsearch\' of undefined',
  }

  Object.<anonymous> (index.js:23:25)
  extensions.(anonymous function) (node_modules/require-precompiled/index.js:16:3)
  Object.require.extensions.(anonymous function) (node_modules/proxyquire/lib/proxyquire.js:305:43)
  Proxyquire._withoutCache (node_modules/proxyquire/lib/proxyquire.js:215:12)
  Proxyquire.load (node_modules/proxyquire/lib/proxyquire.js:129:15)
  proxyquire (test/index.test.js:43:14)
  Test.getSample [as fn] (test/index.test.js:94:18)
```

**Comment by fhinkel** [comment]
Awesome thanks!

**Comment by fhinkel** [comment]
Sorry, the linter complained. Can you run `npm run lint -- --fix` in the parent directory please.

**Comment by jingweno** [comment]
```
npm run lint -- --fix
npm ERR! missing script: lint

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jou/.npm/_logs/2019-01-30T19_47_41_084Z-debug.log
```

There's no `lint` script in `package.json`

**Comment by jingweno** [comment]
Never mind, it's in the root `package.json`. It should be fixed now.

**Comment by jingweno** [comment]
@fhinkel I can't access any of the CI links. Can you help fix the errors?

**Comment by bhuyiaelectronics1** [comment]
bhuyia electtronics organisizton online adversiting hosting, youtube liive stream, softwear, music video, device unlock

**Pull request merged**
