### PR TITLE
chore(functions): Move tests to Node 14 image

### PR DESCRIPTION
**Pull request by ace-n**
~Part of~ Fixes **b/171596650**.

### CODE REVIEW

**Review by grant — DISMISSED** [review]
But GCF Node 14 is not available to the public. We should not test samples against 14 if the public can't use it.

**Review by engelke — APPROVED** [review]
LGTM

**Comment by ace-n** [comment]
Let's hold off on this for now. (Googlers - see the bug mentioned above for more details.)

**Review by fhinkel — APPROVED** [review]
LGTM once GCF Node.js 14 is GA.

**Pull request merged**
